apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-4fyx
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-4fyx
    app.kubernetes.io/part-of: ci10t-776-0079-app
  name: devfile-sample-4fyx
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-4fyx
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-4fyx
    spec:
      containers:
      - image: quay.io/pmacik-testing/ci10t-776-0079-tenant/ci10t-776-0079-app/devfile-sample-4fyx@sha256:2ff1fb7b08e3b29e9f5f7dfd424843876145df5b076a7c928b50b85dbf8d2a66
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
